#!/usr/bin/env python3
"""Merge the .bib files into one de-duplicated file, first occurrence winning.

Why this exists: references.bib is being curated by hand, and entries are moving
into it from suggested_refs.bib one at a time. Every migration leaves the key
defined in BOTH files, and a repeated entry is a BibTeX *error* -- it stops
emitting, the .bbl comes out truncated, and every citation in the paper reads as
undefined. Nothing in the LaTeX log says why; you have to read the .blg.

Order matters: references.bib is listed first, so the hand-curated version of a
key is the one that survives. Delete this script once migration is finished and
`\\bibliography{references}` resolves everything on its own.
"""
import re
import sys

SOURCES = ["references.bib", "suggested_refs.bib", "vizij_suggested_refs.bib"]
OUT = "merged_refs.bib"

entry_re = re.compile(r'^@(\w+)\s*\{\s*([^,\s]+)\s*,', re.M)


def entries(text):
    """Yield (key, entry_text). Brace-counts, so nested braces in titles are safe."""
    for m in entry_re.finditer(text):
        if m.group(1).lower() in ("comment", "string", "preamble"):
            continue
        # Start at the entry's OWN opening brace, not at m.end(): the regex
        # consumes it, so scanning from there counts the first field's braces as
        # the entry's and closes after one line.
        i, depth = text.index("{", m.start()), 0
        while i < len(text):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        yield m.group(2), text[m.start():i + 1]


seen, out, dups = {}, [], []
for src in SOURCES:
    try:
        text = open(src).read()
    except FileNotFoundError:
        print(f"  (skipping absent {src})", file=sys.stderr)
        continue
    for key, body in entries(text):
        if key in seen:
            dups.append(f"{key}: kept {seen[key]}, dropped duplicate in {src}")
            continue
        seen[key] = src
        out.append(body)

with open(OUT, "w") as f:
    f.write("% GENERATED by merge_bibs.py -- do not edit; edit the sources.\n")
    f.write("% Sources, in precedence order: " + ", ".join(SOURCES) + "\n\n")
    f.write("\n\n".join(out) + "\n")

print(f"{OUT}: {len(seen)} entries from {len(SOURCES)} files")
for d in dups:
    print("  dedup:", d)
